#!/bin/dash

# See: https://zrajm.org/pagethumb/

cd "${0%/*}/firefox-extension" || exit 5

VERSION="$(grep -Po '(?<="version": ").*?(?=")' manifest.json)"
ZIPFILE="pagethumb-$VERSION.xpi"
echo "building: $ZIPFILE"

rm -f ../"$ZIPFILE" || exit 5

# Add files in alphabetical order.
git ls-files | \
    LC_COLLATE=C sort | \
    zip -@ ../"$ZIPFILE"

#EOF
