#!/bin/dash

# See: https://zrajm.org/pagethumb/
cd ${0%/*}/firefox-extension || exit 5
rm -f ../pagethumb.xpi || exit 5

# Add files in alphabetical order.
find . -type f | \
    LC_COLLATE=C sort | \
    zip -@ ../pagethumb.xpi --exclude '#*#' '.#*' '*~' '*.bak' '*.tmp'

#EOF
